### ISSUE TITLE
DBM TCP Network Interface

### ISSUE THREAD

**Issue by alexv-anderson** [bcroden/LMS#1]

**Comment by alexv-anderson** [comment]
I just pushed a basic form of a threaded TCP server. @bcroden, what kind of interface will you need for the encryption module to communicate with the network module?

**Comment by bcroden** [comment]
The basic premise of the symmetrical cryptography class is that the cryptography objects will have an encrypt() method, and a decrypt() method. While the decryption method will output a string, the best input would be a byte[] containing the raw bytes transmitted from the network. This is because converting the byte[] to a String usually messes up the padding for the encrypted bytes, and fixing that is probably harder then just using a byte[] in the first place.
So a prototype would be something like:

byte[] encrypt(String message); //Returns encryptedBytes
String decrypt(byte[] encryptedBytes); //Returns message

Please let me know if this doesn't make any sense, or if I am just crazy and there is a much easier way to go about it. Also, I will be working on the symmetrical cryptography class tonight and will hopefully have something basic up soon.
