### ISSUE TITLE
DBM Message Formatting

### ISSUE THREAD

**Issue by alexv-anderson** [bcroden/LMS#5]
Create issue and assign milestone per our meeting last Thursday.

**Comment by alexv-anderson** [comment]
Hey, @ctr002, glad to see that you were able to make some progress with the query objects. @rxm033, is this enough for you to push a version of the Authentication package?

**Comment by rxm033** [comment]
Sorry I've been busy all weekend. I'll put it up later today

**Comment by ctr002** [comment]
I think I've got something up that should run but I didn't compile and run all of the code together. Let me know if there is an error and I'll fix it.

**Comment by CadeG** [comment]
I just pushed a database wrapper that can manage 2.1, 2.2, and 2.3
queries.  Also the 1.1 website functionality is still all good.  Let me
know if there needs to be adjustments (or testing because it may only work
for me since only I have the database).  The Main also has examples of
calling and receiving data from my class.

-Cade

**Comment by rxm033** [comment]
Ok I cannot tell how the Query object is going to be arranging is string
and how its going to be passing it to me.

**Comment by rxm033** [comment]
Nevermind, got it

**Comment by rxm033** [comment]
I'm going to need some clarification on how the session ID's are going to
work before I can get my code up and running. I thought I understood how
they were to be used but I realized that I do not.
1) Am I going to be passing them back to networking?
2) How are they going to be passed to me?
3) Do I need to keep track of them in any other way than adding them to a
hash map?
